language: java
sudo: true
jdk:
  - openjdk11
  - oraclejdk11
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
env:
addons:
#before_install:
  # - sudo apt-get update
  # - sudo apt-get install -y dbus dbus-java-bin dbus-x11
  # - sudo apt-get install -y gnome-session gnome-keyring libsecret-1-0
install:
script:
  - mvn compile
  # - mvn clean test verify -P coverage
after_success:
before_deploy:
deploy:
tags: true
